config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  root "tasks#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/completed_task.rb
class CompletedTask < ApplicationRecord
end

app/models/duedate_search.rb
class DuedateSearch
    attr_reader :date_from, :date_to

    def initialize(params)
        params ||= {}
        @date_from = parsed_date(params[:date_from],30.days.ago.to_date.to_s)
        @date_to = parsed_date(params[:date_to], 90.days.from_now.to_date.to_s)
    end

    def scope 
        Task.where('duedate BETWEEN ? AND ?', @date_from, @date_to)
    end
    
    private

    def parsed_date(date_string, default)
        Date.parse(date_string)
    rescue ArgumentError,TypeError
        default
    end

end

app/models/task.rb
# app/models/task.rb

class Task < ApplicationRecord
  # Define the category as an enum with two options: 'Personal' and 'Work'
  enum category: { personal: 'Personal', work: 'Work' }
  
  # Validations (you can customize these as needed)
  validates :name, presence: true
  validates :category, inclusion: { in: categories.keys }
  validates :duedate, presence: true
  validate :duedatepast
  
  def duedatepast
    if duedate.present? && duedate < Date.today
      errors.add(:duedate, "can't be in the past") 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def sort_date
        
        @tasks = Task.order('created_at DESC')
        
    end
end

app/controllers/tasks_controller.rb
# app/controllers/tasks_controller.rb

class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  #-----------------------------------------------------------------------------  
    # Use the sort_column and sort_direction methods to set the sorting parameters
    #@sort_column = sort_column
    #@sort_direction = sort_direction
    #@products = Product.order("#{@sort_column} #{@sort_direction}")
  #----------------------------------------------------------------------------- 
  
    @search = DuedateSearch.new(params[:search])
    @tasks = @search.scope
    #query by due date ^
    
  end
#-------------------------------------------------------------------------------
  #def order_column
  #  Product.column_names.include?(params[:sort_column]) ? params[:sort_column] : "name"
  #end
  
  #def sort_direction
  #  %w[asc desc].include?(params[:sort_direction]) ? params[:sort_direction] : "asc"
  #end
#-------------------------------------------------------------------------------
  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  # In your TasksController
  # app/controllers/tasks_controller.rb
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_url, notice: 'Task was successfully deleted.'
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:name, :description, :category, :duedate, :completed)
  end





end

app/helpers/application_helper.rb
module ApplicationHelper
    def sortable(column, title = nil)
      title ||= column.titleize
      css_class = column == sort_column ? "current #{sort_direction}" : nil
      direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
      link_to title, {:sort => column, :direction => direction}, {:class => css_class}
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag 'tasks' %>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag 'https://cdn.datatables.net/1.11.6/css/jquery.dataTables.min.css' %>
    <%= javascript_include_tag 'https://code.jquery.com/jquery-3.6.0.min.js' %>
    <%= javascript_include_tag 'https://cdn.datatables.net/1.11.6/js/jquery.dataTables.min.js' %>


    
    <title>TaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script>
    document.addEventListener('DOMContentLoaded', function () {
      const increaseButton = document.getElementById('increase-font-size');
      const decreaseButton = document.getElementById('decrease-font-size');
      const body = document.body;
    
      let currentFontSize = 16; // The initial font size (in pixels)
    
      increaseButton.addEventListener('click', function () {
        currentFontSize += 2; // Increase font size by 2 pixels
        body.style.fontSize = currentFontSize + 'px';
      });
    
      decreaseButton.addEventListener('click', function () {
        currentFontSize -= 2; // Decrease font size by 2 pixels
        body.style.fontSize = currentFontSize + 'px';
      });
    });
  </script>


  </head>

  <body>
    <button id="increase-font-size">Increase Font Size</button>
    <button id="decrease-font-size">Decrease Font Size</button>
    <%= yield %>
    

  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div style="margin-bottom: 25px;">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>
<br>
  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.select :category, [['Personal', 'personal'], ['Work', 'work']] %>
  </div>
<br>
  <div>
    <%= form.label :duedate, style: "display: block" %>
    <%= form.date_field :duedate, value: Date.current %>
  </div>
<br>
  <div style="margin-top: 15px;">
  <%= form.label :completed, style: "display: inline-block; margin-right: 10px; vertical-align: middle; " %>
  <%= form.check_box :completed, style: "vertical-align: middle;" %>
  </div>
<br>
  <div>
    <%= form.submit class: "custom-button" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Name:</strong>
    <%= task.name %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= task.status %>
  </p>

  <p>
    <strong>Order:</strong>
    <%= task.order %>
  </p>

  <p>
    <strong>Duedate:</strong>
    <%= task.duedate %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= task.location %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= task.description %>
  </p>

</div>

app/views/tasks/edit.html.erb
<div class="centered-content">
  <h1>Editing Task</h1>

  <div class="form-container">
    <%= render 'form', task: @task %>
  </div>
  
  <div class="action-buttons">
    <%= link_to 'Show Task', @task, class: 'button' %> 
    <%= link_to 'Back to Tasks', tasks_path, class: 'button' %>
  </div>
</div>

app/views/tasks/index.html.erb
<html>
  
<head>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">
  <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>
</head>

<br>
<br>

<body>

<div id="notice"><%= notice %></div>

<br>

<div class="header-content">
 <h1 class="heading">TASK MANAGER</h1>
  <%= link_to 'Create New Task', new_task_path, class: 'green-task-button' %>
</div>



<br>
<br>

<div class="dataTables_filter">
  <label for="name-filter">Name:</label>
  <input type="text" id="name-filter">
  <label for="description-filter">Description:</label>
  <input type="text" id="description-filter">
  
  <label for="category-filter">Category:</label>
  <select id="category-filter">
    <option value="">All</option>
    <option value="Personal">Personal</option>
    <option value="Work">Work</option>
  </select>
  
  <label for="completed-filter">Completed:</label>
  <select id="completed-filter">
    <option value="">All</option>
    <option value="true">Completed</option>
    <option value="false">Not Completed</option>
  </select>
</div>

<br>
<br>
<br>

<div class = "pull-right range-query">
  <%= form_tag tasks_path, method: :get do %>
    <%=text_field_tag 'search[date_from]' , @search.date_from %>
    <%=text_field_tag 'search[date_to]' , @search.date_to %>
    <%= submit_tag 'Search', class: 'btn search-button'%>
  <%end%>
</div>

<table id="tasks-table" class="display">
  <thead>
    <tr>
      <th class="sortable">Date Added</th>
      <th class="sortable">Task Name</th>
      <th>Task Description</th>
      <th class="sortable">Task Category</th>
      <th class="sortable">Task Due Date</th>
      <th class="sortable">Task Completed</th>
      <th>Controls</th>
    </tr>
  </thead>

<tbody>
  <% @tasks.each do |task| %>
    <tr>
      <td class="<%= task.category.parameterize%> <%='completed-task' if task.completed %>" ><%= task.created_at.in_time_zone('Hawaii').strftime("%B %d %Y") %></td>
      <td class="<%= task.category.parameterize%> <%='completed-task' if task.completed %>" ><%= task.name %></td>
      <td class="<%= task.category.parameterize%> <%='completed-task' if task.completed %>" ><%= task.description %></td>
      <td class="<%= task.category.parameterize%> <%='completed-task' if task.completed %>" ><%= task.category %></td>
      <td class="<%= task.category.parameterize%> <%='completed-task' if task.completed %>" ><%= task.duedate.strftime("%B %d %Y") %></td>
      <td class="<%= task.category.parameterize%> <%='completed-task completed-task-settings' if task.completed %>">
          <%= task.completed ? 'Task Completed' : 'Not Completed' %>
      </td>
      </td>
      <td class="<%= task.category.parameterize%> <%='completed-task-settings' if task.completed %>">
        <%= link_to 'SHOW', task, class: 'blue-show-button' %>
        <%= link_to 'EDIT', edit_task_path(task), class: 'blue-edit-button' %>
        <br>
        <%= button_to 'Delete', task, method: :delete, class: 'delete-button', onclick: 'confirmDelete(event)' %>

      </td>
    </tr>
  <% end %>
</tbody>
</table>

<script type="text/javascript">
  function confirmDelete(event) {
    if (confirm('Are you sure you want to delete this task?')) {
      // If the user confirms, continue with the deletion action.
      return true;
    } else {
      // If the user cancels, prevent the default action (deletion).
      event.preventDefault();
      return false;
    }
  }

  $(document).ready(function() {
  var table = $('#tasks-table').DataTable({
    "order": [], // Initialize with no default sorting

    // Define sorting options for specific columns
    "columnDefs": [
      {
        "targets": 'sortable', // Add the "sortable" class to the th elements you want to make sortable
        "orderable": true, // Enable sorting for these columns
      },
    ]
  });

  // Apply individual column filtering for each input
  $('#name-filter').on('keyup', function() {
    table.column(1).search(this.value).draw();
  });
  $('#description-filter').on('keyup', function() {
    table.column(2).search(this.value).draw();
  });
  $('#category-filter').on('change', function() {
      var value = this.value;
      if (value === "") {
        table.column(3).search("").draw();
      } else {
        table.column(3).search(value).draw();
      }
    });
  $('#completed-filter').on('change', function() {
    var value = this.value;
    if (value === "") {
      table.column(5).search("").draw();
    } else {
      table.column(5).search(value === "true" ? "Task Completed" : "Not Completed").draw();
    }
  });
});

</script>
</body>
</html>

app/views/tasks/new.html.erb
<div class="centered-content">
  <h1>New task</h1>
  <div class="form-container">
    <%= render "form", task: @task %>
  </div>
  <div class="back-link">
    <%= link_to "Back to tasks", tasks_path %>
  </div>
</div>

app/views/tasks/show.html.erb
<br>
<table>
  <tr>
    <th>Name:</th>
    <th>Description:</th>
    <th>Category:</th>
    <th>Due Date:</th>
    <th>Completed:</th>
  </tr>
  <tr>
    <td><%= @task.name %></td>
    <td><%= @task.description %></td>
    <td><%= @task.category %></td>
    <td><%= @task.duedate %></td>
    <td><%= check_box_tag "task_completed", 1, @task.completed, disabled: true %></td>
  </tr>
</table>

<div class="centered-buttons">
<%= link_to 'Edit this task', edit_task_path(@task) %> |
<%= link_to 'Back to tasks', tasks_path %>

<%= button_to 'Delete Task', task_path(@task), method: :delete, class: 'custom-button2', id: 'delete-task-button' %>


</div>

<script type="text/javascript">
  document.addEventListener("DOMContentLoaded", function() {
    const deleteButton = document.getElementById("delete-task-button");
    deleteButton.addEventListener("click", function(event) {
      if (!confirm('Are you sure you want to delete this task?')) {
        event.preventDefault(); // Prevent the default delete action if the user cancels.
      }
    });
  });
</script>